bt_navigator:
  ros__parameters:
    transform_timeout: 2.0
    transform_tolerance: 0.2
    bt_loop_duration: 10
    default_server_timeout: 20
    default_nav_to_pose_bt_xml: /home/user/ros2_ws/src/warehouse_project/path_planner_server/config/navigate_w_replanning_and_recovery.xml